[workspace]
resolver = "2"

members = [
    "_lib",
    # topics
    "algorithms",
    "data-structures",
    "design-patterns",
    "macros",
    "problem-solving",
    # projects
    "projects/pandas",
    "projects/ruscrypt",
    "projects/vault",
]
