[package]
name = "dynamic_programming"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "fibonacci"
path = "./src/dp001_fibonacci.rs"

[[bin]]
name = 'lcs'
path = "./src/dp002_lcs.rs"
