[package]
name = "smart-pointers"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]


[[bin]]
name = 'box'
path = 'src/box.rs'

[[bin]]
name = 'rc'
path = 'src/rc.rs'

[[bin]]
name = 'refcell'
path = 'src/refcell.rs'

[[bin]]
name = 'arc-mutex'
path = 'src/arc-mutex.rs'

[[bin]]
name = 'cow'
path = 'src/cow.rs'
