[package]
name = "vault"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
directories = "5.0.1"
crypto = "0.5.1"
argon2 = "0.5.3"
aes = "0.8.4"
sha2 = "0.10.8"
cipher = "0.4.4"
block-modes = "0.9.1"
cbc = "0.1.2"
rand = "0.8.5"
